### ISSUE TITLE
Without storyboard error

### ISSUE THREAD

**Issue by chanraksmey** [RobotsAndPencils/RPSlidingMenu#24]
Could I use RPSidingMenu without storyboard ?

iOS App crash with error message:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'UICollectionView must be initialized with a non-nil layout parameter'

Any idea please ?

**Comment by interstateone** [comment]
I'm closing this issue since it was resolved from discussion in #20.
