### ISSUE TITLE
Awesome menu, thank you!

### ISSUE THREAD

**Issue by bigbadleroybrown** [RobotsAndPencils/RPSlidingMenu#26]
Im having an issue getting this to show up following a login. I keep getting this error thrown : 'UICollectionView must be initialized with a non-nil layout parameter'.

Is there a way to show this menu in ViewDidLoad?

Thank you again!

**Comment by interstateone** [comment]
Hi @bigbadleroybrown, please see #20 for steps others have used to use this project outside of a storyboard.
