### ISSUE TITLE
How can I set the spacing between cell ?

### ISSUE THREAD

**Issue by HTKT** [RobotsAndPencils/RPSlidingMenu#27]
I want to set the spacing between cel and and left and right margin? How can i do that? 

Thanks

**Comment by paulthorsteinson** [comment]
Hi @HTKT, it is just a normal collectionview so you should be able to set the minimumLineSpacing value in interface builder or via code and it should work.  See http://stackoverflow.com/questions/13970950/uicollectionview-spacing-margins
