### ISSUE TITLE
Blur Collapsed Images

### ISSUE THREAD

**Issue by docash59** [RobotsAndPencils/RPSlidingMenu#34]
An idea would be if the image in the collapsed cells is blurred until it expand at at the top.
Would be a nice user experience.

**Comment by interstateone** [comment]
Hi @docash59, thanks for the neat idea. This project was originally designed to replicate a view in the UltraVisual 1.0 app, and in the interest of flexibility for users of the project I think the blurring should be optional. If you're interested in contributing this change as a pull request then it would be welcomed. :smile: I'm going to close this issue in the meantime, but let us know here if you have any questions about proceeding with an implementation.
